swagger: "2.0"
info:
  title: Postboard
  description: API for Postboard
  version: "${VERSION_MAJOR}.${VERSION_MINOR}"
basePath: "/v${VERSION_MAJOR}"
host: ${HOST}
schemes:
  - https
produces:
  - application/json
paths:
  /random_word:
    get:
      summary: Return a random word
      operationId: GET__random_word
      x-google-backend:
        address: ${GET__random_word}
      responses:
        '200':
          description: A randomly-selected word
          schema:
            type: string
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"